language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
before_script:
  - bundle exec rake db:migrate
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
      rvm: ruby-head
env:
  - "RAILS_VERSION=3.2.19"
  - "RAILS_VERSION=4.1.4"
  - "RAILS_VERSION=master"
