language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
before_script:
  - bundle exec rake db:migrate
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.gemfile
